export const DATABASE = {
    TABLES: {
        PROFILES: 'PROFILES',
        WS_CUSTOMERS: 'WS_CUSTOMERS',
        WS_CUSTOMERS_2: 'WS_CUSTOMERS_2',
        WS_LEADS: 'WS_LEADS', 
        WS_PAYMENTS: 'WS_PAYMENTS',
        WS_POLICIES: 'WS_POLICIES',
        WS_TASKS: 'WS_TASKS',
        WS_USER_GOALS: 'WS_USER_GOALS', 
        WS_GOALS: 'WS_GOALS',
        WS_IA_CONVERSATIONS: 'WS_IA_CONVERSATIONS',
        WS_IA_MESSAGES: 'WS_IA_MESSAGES',
        WS_GMAIL_CONNECTIONS: 'WS_GMAIL_CONNECTIONS',
        WS_GMAIL_SENT_EMAILS: 'WS_GMAIL_SENT_EMAILS',
        WS_SCHEDULED_EMAILS: 'WS_SCHEDULED_EMAILS',
        WS_EMAIL_SIGNATURES: 'WS_EMAIL_SIGNATURES',
        WS_EMAIL_TEMPLATES: 'WS_EMAIL_TEMPLATES',
        WS_CALENDLY_CONNECTIONS: 'WS_CALENDLY_CONNECTIONS',
        WS_CALENDLY_EVENT_TASKS: 'WS_CALENDLY_EVENT_TASKS',
        WS_AUTOMATIONS: 'WS_AUTOMATIONS',
        WS_AUTOMATION_LOGS: 'WS_AUTOMATION_LOGS',
    },
    BUCKETS:{
        TU_LOGO: 'tu-logo',
        EMAIL_TEMPLATE_ASSETS: 'email-template-assets',
    }
}